// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebReckrytingSystem.Models;

#nullable disable

namespace WebReckrytingSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251203190242_addadmin")]
    partial class addadmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebReckrytingSystem.Models.Company", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("logo_url");

                    b.Property<bool>("Verified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("verified");

                    b.Property<string>("Website")
                        .HasColumnType("longtext")
                        .HasColumnName("website");

                    b.HasKey("Name");

                    b.ToTable("companies", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebReckrytingSystem.Models.Resume", b =>
                {
                    b.Property<string>("UserEmail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_email");

                    b.Property<string>("DesiredPosition")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("desired_position");

                    b.Property<string>("EducationDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("education_description");

                    b.Property<string>("ExperienceDescription")
                        .HasColumnType("longtext")
                        .HasColumnName("experience_description");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<string>("PracticesJson")
                        .HasColumnType("text")
                        .HasColumnName("practices_json");

                    b.Property<int?>("SalaryExpectations")
                        .HasColumnType("int")
                        .HasColumnName("salary_expectations");

                    b.Property<string>("Skills")
                        .HasColumnType("longtext")
                        .HasColumnName("skills");

                    b.HasKey("UserEmail");

                    b.ToTable("resumes", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebReckrytingSystem.Models.User", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.HasKey("Email");

                    b.ToTable("users", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebReckrytingSystem.Models.Vacancy", b =>
                {
                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("company_name");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("AuthorEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("author_email");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("employment_type");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("requirements");

                    b.Property<int?>("SalaryFrom")
                        .HasColumnType("int")
                        .HasColumnName("salary_from");

                    b.Property<int?>("SalaryTo")
                        .HasColumnType("int")
                        .HasColumnName("salary_to");

                    b.Property<string>("WorkSchedule")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("work_schedule");

                    b.HasKey("CompanyName", "Title");

                    b.HasIndex("AuthorEmail");

                    b.ToTable("vacancies", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("WebReckrytingSystem.Models.Resume", b =>
                {
                    b.HasOne("WebReckrytingSystem.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("WebReckrytingSystem.Models.Resume", "UserEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebReckrytingSystem.Models.Vacancy", b =>
                {
                    b.HasOne("WebReckrytingSystem.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebReckrytingSystem.Models.Company", "Company")
                        .WithMany("Vacancies")
                        .HasForeignKey("CompanyName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("WebReckrytingSystem.Models.Company", b =>
                {
                    b.Navigation("Vacancies");
                });
#pragma warning restore 612, 618
        }
    }
}
